global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.JSInterop;
global using MinecraftCommandBuilder;
global using MinecraftCommandBuilder.Services;
global using MinecraftDataCSharp;
global using MinecraftDataCSharp.Repositories;
global using MudBlazor;
global using MudBlazor.Services;
global using Block = MinecraftDataCSharp.Repositories.Block;
