global using System.ClientModel;
global using System.Text;
global using Azure.AI.OpenAI;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.Extensions.AI;
global using Microsoft.JSInterop;
global using MinecraftCommandBuilder;
global using MinecraftCommandBuilder.Models;
global using MinecraftCommandBuilder.Services;
global using MinecraftDataCSharp;
global using MinecraftDataCSharp.Repositories;
global using MudBlazor;
global using MudBlazor.Services;
global using Block = MinecraftDataCSharp.Repositories.Block;
